### ISSUE TITLE
Create a README file

### ISSUE THREAD

**Issue by Palakkgoyal** [Palakkgoyal/Button-Mania#2]
This project need a README file which contain:
->how to setup button-mania(forking the repo, cloning it, React setup using vite)
->how to contribute to the project and what are the guidelines
->how to send a merge-pull request

**Comment by yr1404** [comment]
I'd like to work on it.

**Comment by Palakkgoyal** [comment]
Sure, you can start working on it

**Comment by Palakkgoyal** [comment]
First, create a set up guide then, I will tell you about how one can contribute to it

**Comment by yr1404** [comment]
Done [#4 ](url)

**Comment by Palakkgoyal** [comment]
The server you provided in line 51 is not of React. The React server starts at `localhost:5173`

**Comment by Palakkgoyal** [comment]
Can you make a new file for the set up and give a link to that file in the README and in the README tell the users how to contribute

**Comment by Palakkgoyal** [comment]
How to contribute?
Step 1) Create a button on codepen.io
Step 2) Take its screenshot
Step 3) Add the screenshot in the assets folder with a name that not exist earlier and and tell how the button looks.
Step 4) In the assets folder go to index.js, import the button image and export it
Step 5) Go to components > Buttons > AllButtons.jsx
Step 6) Create a ButtonCard component and pass it all the props required
Example: 
<ButtonCard 
        btnImg={ neumorphicGreyBtn } 
        imgAlt="neumorphic grey button"
        codepenLink="https://codepen.io/Palak-Goyal/pen/dygEaVp"
        zipFileName='trial-button'
        authorName="Palak Goyal"
        githubLink="https://github.com/palakkgoyal"
      />

Step 6) Send the PR

**Comment by Palakkgoyal** [comment]
In the set up please also tell that they should make a new branch to contribute

**Comment by yr1404** [comment]
> The server you provided in line 51 is not of React. The React server starts at `localhost:5173`

Okay. I will change it.

**Comment by yr1404** [comment]
I've made all the changes.

**Comment by Palakkgoyal** [comment]
That's great. I have merged your PR. Thanks for contributing.
